#!/command/with-contenv bash

set -e

# Export variables (with defaults) to make them available to all child processes
export KOHA_INSTANCE=${KOHA_INSTANCE:-default}
export KOHA_INTRANET_PORT=${KOHA_INTRANET_PORT:-8080}
export KOHA_OPAC_PORT=${KOHA_OPAC_PORT:-8081}
export USE_MEMCACHED=${USE_MEMCACHED:-no}
export MEMCACHED_SERVERS=${MEMCACHED_SERVERS:-memcached:11211}
export MYSQL_SERVER=${MYSQL_SERVER:-mariadb}
export MYSQL_PASSWORD=${MYSQL_PASSWORD:-$(pwgen -s 15 1)}
export ZEBRA_MARC_FORMAT=${ZEBRA_MARC_FORMAT:-marc21}
export MYSQL_ROOT_USER=${MYSQL_ROOT_USER:-root}

# RabbitMQ (Message Broker) settings
export MB_HOST=${MB_HOST:-rabbitmq}
export MB_PORT=${MB_PORT:-61613} # Stomp TCP listens on 61613 by default
export MB_USER=${MB_USER:-guest}
export MB_PASS=${MB_PASS:-guest}

MB_PARAMS="--mb-host ${MB_HOST} --mb-port ${MB_PORT} --mb-user ${MB_USER} --mb-pass ${MB_PASS}"

echo "Running startup script..."

# Fill in the values in our configuration file and write it to the place Koha reads it from
envsubst < /docker/config/koha-sites.conf > /etc/koha/koha-sites.conf

echo -n "${KOHA_INSTANCE}:koha_${KOHA_INSTANCE}:${MYSQL_PASSWORD}:koha_${KOHA_INSTANCE}:${MYSQL_SERVER}" > /etc/koha/passwd

# Use helper functions (if present), otherwise exit
if [ ! -f "/usr/share/koha/bin/koha-functions.sh" ]
then
    echo "koha-functions should be present" 1>&2
    exit 1
fi

source /usr/share/koha/bin/koha-functions.sh

if ! is_instance ${KOHA_INSTANCE} || [ ! -f "/etc/koha/sites/${KOHA_INSTANCE}/koha_conf.xml" ]
  then
      echo "Executing koha-create for instance ${KOHA_INSTANCE}"
      koha-create ${MB_PARAMS} --use-db ${KOHA_INSTANCE} | true
  else
      echo "Creating directories structure"
      koha-create-dirs ${KOHA_INSTANCE}
fi

service apache2 stop

# Koha gets grumpy if the OPAC and intranet logs don't exist
touch /var/log/koha/${KOHA_INSTANCE}/opac-error.log /var/log/koha/${KOHA_INSTANCE}/intranet-error.log

# Give the Koha instance user ownership of the log directory to avoid permission errors
chown -R ${KOHA_INSTANCE}-koha:${KOHA_INSTANCE}-koha /var/log/koha/${KOHA_INSTANCE}/

# Enable and start the Plack server for the Koha instance
koha-plack --enable ${KOHA_INSTANCE}
