services:
  mariadb:
    image: mariadb:${MARIADB_VERSION:-10.6}
    restart: ${RESTART_POLICY:-no}
    volumes:
      - mariadb-storage:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - '${MYSQL_SERVER_PORT:-3306}:${MYSQL_SERVER_PORT:-3306}'
    env_file:
      - .env

  memcached:
    image: memcached:${MEMCACHED_VERSION:-latest}
    restart: ${RESTART_POLICY:-no}
    ports:
      - '${MEMCACHED_PORT:-11211}:${MEMCACHED_PORT:-11211}'
    healthcheck:
      test: ["CMD-SHELL", "/bin/bash -c 'exec 3<>/dev/tcp/localhost/11211; printf \"stats\nquit\n\" >&3'"]
      start_period: 10s
      interval: 30s
      timeout: 10s
      retries: 3
    command:
      - --conn-limit=1024
      - --memory-limit=64
      - --threads=4

  rabbitmq:
    image: rabbitmq:${RABBITMQ_VERSION:-latest}
    restart: ${RESTART_POLICY:-no}
    volumes:
      - './rabbitmq-plugins:/etc/rabbitmq/enabled_plugins'
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      start_period: 10s
      interval: 30s
      timeout: 10s
      retries: 3

  koha:
    build:
      context: ./koha
      dockerfile: Dockerfile
    restart: ${RESTART_POLICY:-no}
    ports:
      - '${KOHA_INTRANET_PORT:-8080}:${KOHA_INTRANET_PORT:-8080}'
      - '${KOHA_OPAC_PORT:-8081}:${KOHA_OPAC_PORT:-8081}'
    cap_add:
      - SYS_NICE
      - DAC_READ_SEARCH
    depends_on:
      mariadb:
        condition: service_started
      memcached:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    env_file:
      - .env

volumes:
  mariadb-storage:
