services:
  mariadb:
    image: mariadb:${MARIADB_VERSION:-10.6}
    restart: ${RESTART_POLICY:-no}
    volumes:
      - mariadb-storage:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - '${MYSQL_SERVER_PORT:-3306}:${MYSQL_SERVER_PORT:-3306}'
    env_file:
      - default.env

  koha:
    build:
      context: ./koha
      dockerfile: Dockerfile
    restart: ${RESTART_POLICY:-no}
    ports:
      - '${KOHA_INTRANET_PORT:-8080}:${KOHA_INTRANET_PORT:-8080}'
      - '${KOHA_OPAC_PORT:-8081}:${KOHA_OPAC_PORT:-8081}'
    cap_add:
      - SYS_NICE
      - DAC_READ_SEARCH
    depends_on:
      mariadb:
        condition: service_started
    env_file:
      - default.env

volumes:
  mariadb-storage:
